[tool.poetry]
name = "kubernetes-learning"
version = "0.1.0"
description = ""
authors = ["Illia Troshchynskyi <illia.troshchynskyi@nixs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
