apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
  namespace: "{{ .Values.appName.name}}-{{ .Values.environment.env}}"
spec:
  provider:
    aws:
      service: ParameterStore
      region:  us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            namespace: external-secrets
            key: accessKeyId

          secretAccessKeySecretRef:
            name: aws-credentials
            namespace: external-secrets
            key: secretAccessKey