apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password-sync
  namespace: "{{ .Values.appName.name}}-{{ .Values.environment.env}}"
spec:
  refreshInterval: "0h" # if not 0 then it is influenced on the costs
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  target:
    name: db-credentials # The name of the K8s Secret to create
    creationPolicy: Owner

  data:
  - secretKey: SUPER_PASSWORD_DB # The key inside the 'db-credentials' secret
    remoteRef:
      # This is the exact path parameter in AWS Parameter Store
      key: /dev/SUPER_PASSWORD_DB