apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    # We only need to specify the ingress class
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: your-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Make sure this is the exact name of your frontend service
            name: {{ .Values.frontendApp.serviceName }}-{{  .Values.environment.env}}
            port:
              number: {{ .Values.frontendApp.port }}