apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-app-config
  namespace: "{{ .Values.appName.name}}-{{ .Values.environment.env}}"
data:
  VITE_BASE_URL: ""
  VITE_ENV: "{{ .Values.environment.env}}"
  VITE_DESCRIPTION: "Description"