build_app:
	docker image build -t react-app:v1.0 .


run_app_docker:
	docker run -dp 80:80 react-app:v1.0

tag:
	docker tag react-app:v1.0 ilya0108/react-app:v1.0

push:
	docker push ilya0108/react-app:v1.0